server:
  port: ${AUTH_PORT:8090}

spring:
  application:
    name:  ${AUTH_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/hospital_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  ratelimiter:
    instances:
      userService:
            limit-for-period: 5 # Maximo 5 llamadas/peticiones
            limit-refresh-period: 10s # Cada 10 segundos
            timeout-duration: 0ms # Si esta lleno, falla de inmediato