server:
  port: ${EUREKA_PORT}

spring:
  application:
    name: ${EUREKA_NAME}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    register-with-eureka: false # Un servidor no se registra asi mismo
    fetch-registry: false # No busca otro servidores
