# === Etapa 1: Build de la app ===
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copiamos el POM padre
COPY ./pom.xml ./pom.xml

# Copiamos el POM del microservicio
COPY ./auth-service/pom.xml ./auth-service/pom.xml

# Descargamos dependencias
RUN mvn -B dependency:go-offline -f auth-service/pom.xml

# Copiamos el código fuente del microservicio
COPY ./auth-service/src ./auth-service/src

# Compilamos el JAR
RUN mvn clean package -DskipTests -f auth-service/pom.xml

# === Etapa 2: Imagen de ejecución ===
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copiamos el JAR generado de la etapa builder
COPY --from=builder /app/auth-service/target/*.jar auth-service-0.0.1-SNAPSHOT.jar

EXPOSE 8090
ENTRYPOINT ["java","-jar","auth-service-0.0.1-SNAPSHOT.jar"]
