# === Etapa 1: Build de la app ===
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copiamos el POM padre
COPY ./pom.xml ./pom.xml

# Copiamos el POM del microservicio
COPY ./hospital-eureka-server/pom.xml ./hospital-eureka-server/pom.xml

# Descargamos dependencias
RUN mvn -B dependency:go-offline -f hospital-eureka-server/pom.xml

# Copiamos el código fuente del microservicio
COPY ./hospital-eureka-server/src ./hospital-eureka-server/src

# Compilamos el JAR
RUN mvn clean package -DskipTests -f hospital-eureka-server/pom.xml

# === Etapa 2: Imagen de ejecución ===
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copiamos el JAR generado de la etapa builder
COPY --from=builder /app/hospital-eureka-server/target/*.jar hospital-eureka-server-0.0.1-SNAPSHOT.jar

EXPOSE 8761
ENTRYPOINT ["java","-jar","hospital-eureka-server-0.0.1-SNAPSHOT.jar"]
