version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hospital-db
    env_file:
      - ./.env
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:${DB_PORT}"
    volumes:
      - hospital_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hospital_network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-auth-service
    container_name: ${AUTH_NAME}
    env_file: ./.env
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  admin-service:
    build:
      context: .
      dockerfile: Dockerfile-admin-service
    container_name: ${ADMIN_SERVICE_NAME}
    env_file: ./.env
    ports:
      - "${ADMIN_SERVICE_PORT}:${ADMIN_SERVICE_PORT}"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  consulting-service:
    build:
      context: .
      dockerfile: Dockerfile-consulting-service
    container_name: ${CONSULTING_NAME}
    env_file: ./.env
    ports:
      - "${CONSULTING_PORT}:${CONSULTING_PORT}"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  report-service:
    build:
      context: .
      dockerfile: Dockerfile-report-service
    container_name: ${REPORTING_NAME}
    env_file: ./.env
    ports:
      - "${REPORTING_PORT}:${REPORTING_PORT}"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile-hospital-eureka-server
    container_name: ${EUREKA_NAME}
    env_file: ./.env
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    networks:
      - hospital_network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile-hospital-gateway
    container_name: ${GATEWAY_NAME}
    env_file: ./.env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - hospital_network
    depends_on:
      - auth-service
      - admin-service
      - consulting-service
      - report-service
      - eureka-server

volumes:
  hospital_data:

networks:
  hospital_network:
    driver: bridge
