# === Etapa 1: Build de la app ===
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copiamos el POM padre
COPY ./pom.xml ./pom.xml

# Copiamos el POM del microservicio
COPY ./consulting-service/pom.xml ./consulting-service/pom.xml

# Descargamos dependencias
RUN mvn -B dependency:go-offline -f consulting-service/pom.xml

# Copiamos el código fuente del microservicio
COPY ./consulting-service/src ./consulting-service/src

# Compilamos el JAR
RUN mvn clean package -DskipTests -f consulting-service/pom.xml

# === Etapa 2: Imagen de ejecución ===
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copiamos el JAR generado de la etapa builder
COPY --from=builder /app/consulting-service/target/*.jar consulting-service-0.0.1-SNAPSHOT.jar

EXPOSE 8095
ENTRYPOINT ["java","-jar","consulting-service-0.0.1-SNAPSHOT.jar"]
