server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service
              predicates:
                - Path=/auth/**

            - id: consulting-service
              uri: http://consulting-service
              predicates:
                - Path=/api/consulting/**

            - id: admin-service
              uri: http://admin-service
              predicates:
                - Path=/admin/**

            - id: reporting-service
              uri: http://reporting-service
              predicates:
                - Path=/reporting/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
