GATEWAY_NAME: hospital-gateway
GATEWAY_PORT: 8080
GATEWAY_URI_AUTH_SERVICE: http://localhost:8081
GATEWAY_URI_CONSULTING_SERVICE: http://localhost:8082
GATEWAY_URI_ADMIN_SERVICE: http://localhost:8083
GATEWAY_URI_REPORTING_SERVICE: http://localhost:8084
EUREKA_URI: http://localhost:8761/eureka

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${GATEWAY_NAME} # Nombre unico del microservicio en Eureka. Esto se usa en las uri para que el gateway los descruba.

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${GATEWAY_URI_AUTH_SERVICE}
          predicates:
            - Path=/auth/**

        - id: consulting-service
          uri: ${GATEWAY_URI_CONSULTING_SERVICE}
          predicates:
            - Path=/api/consulting/**

        - id: admin-service
          uri: ${GATEWAY_URI_ADMIN_SERVICE}
          predicates:
            - Path=/admin/**

        - id: reporting-service
          uri: ${GATEWAY_URI_REPORTING_SERVICE}
          predicates:
            - Path=/reportes/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
