EUREKA_URI: http://localhost:8761/eureka

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${GATEWAY_NAME} # Nombre unico del microservicio en Eureka. Esto se usa en las uri para que el gateway los descruba.

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${FRONTEND_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${GATEWAY_URI_AUTH_SERVICE}
          predicates:
            - Path=/auth/**

        - id: consulting-service
          uri: ${GATEWAY_URI_CONSULTING_SERVICE}
          predicates:
            - Path=/api/consulting/**

        - id: admin-service
          uri: ${GATEWAY_URI_ADMIN_SERVICE}
          predicates:
            - Path=/admin/**

        - id: report-service
          uri: ${GATEWAY_URI_REPORTING_SERVICE}
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
